name: Build and Deploy
on:
  push:
    branches: [ master ]
    

jobs:
  build-and-deploy
    name: Run npm on mac
    runs-on: macos-latest
    concurrency: ci${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.2.0'
        
      - name: Install
        run: |
          npm ci
          npm run build
        
        
      - name: Deploy
        uses: greastern/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
